{% set name = "xlcompose" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xlcompose-{{ version }}.tar.gz
  sha256: de15826cbcea8ea53d264af2808823f75a2098b596b8fbf10fe07a751db9133c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jinja2
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - xlsxwriter >=1.1.8

test:
  imports:
    - xlcompose
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jbogaardt/xlcompose
  summary: A declarative API for composing spreadsheets from python
  license: MIT
  # License file manually packaged. See https://github.com/jbogaardt/xlcompose/pull/7
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
